name: Build on Linux

on:
  push:
    branches: [ "devel", "master" ]
  pull_request:
    branches: [ "devel", "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Dependencies
      run: sudo apt-get update && sudo apt-get install -yq
        cmake g++ pkg-config
        libgtk-4-dev libadwaita-1-dev
        libasound2-dev libfluidsynth-dev libuchardet-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
        -DBUILD_DOCS=OFF
        -DBUILD_TESTING=ON
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build --output-on-failure
